# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  boot.initrd.availableKernelModules = [
    "nvme"
    "xhci_pci"
    "usbhid"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [
    "kvm-intel"
  ];
  boot.kernelParams = [
    "nowatchdog"
    "nmi_watchdog=0"
    "intel_idle.max_cstate=1"
  ];
  boot.extraModprobeConfig = ''
    options ath9k nohwcrypt=1 ps_enable=0 btcoex_enable=0
  '';

  boot.extraModulePackages = [

  ];
  # boot.kernelPackages = lib.mkForce pkgs.cachyosKernels.linuxPackages-cachyos-latest-lto-x86_64-v3;
  # boot.kernelPackages = lib.mkForce pkgs.linuxPackages_latest;
  boot.blacklistedKernelModules = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/e4142824-5a8a-4a3f-8a2a-182a05904576";
    fsType = "ext4";
    options = [
      "defaults"
      "discard"
      "noatime"
      "nodiratime"
    ];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/7103-EF40";
    fsType = "vfat";
    options = [
      #"fmask=0022" "dmask=0022"

      "umask=0077"
      "shortname=mixed"
    ];
  };

  # swapDevices = [ { device = "/dev/disk/by-uuid/feee7fba-7baa-42fb-a332-1b915703c5d0"; } ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.eno1.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp7s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
