# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  boot.initrd.availableKernelModules = [
    "nvme"
    "xhci_pci"
    "usbhid"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [
    "kvm-amd"
    "k10temp"
    "zenergy"
    "nct6775"
  ];
  boot.kernelParams = [
    "amd_pstate=active"
    "8250.nr_uarts=0"
  ];
  boot.extraModulePackages = [
    config.boot.kernelPackages.zenergy
  ];
  boot.kernelPackages = lib.mkForce pkgs.cachyosKernels.linuxPackages-cachyos-latest-lto-zen4;
  boot.blacklistedKernelModules = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/e01615ee-1128-44b1-b5f4-3735af0cec57";
    fsType = "ext4";
    options = [
      "defaults"
      "discard"
      "noatime"
      "nodiratime"
    ];
  };

  boot.initrd.luks.devices."luks-root" = {
    device = "/dev/disk/by-uuid/a07c9565-58be-4822-aaf9-85d5e0b2f981";
    allowDiscards = true;
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/B129-239E";
    fsType = "vfat";
    options = [
      "umask=0077"
      "shortname=mixed"
    ];
  };

  # swapDevices = [ { device = "/dev/disk/by-uuid/feee7fba-7baa-42fb-a332-1b915703c5d0"; } ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.eno1.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp7s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
